# This is the configuration file for the BetterDeathDrop plugin

# Set this to true to prevent items from despawning when they are dropped
prevent-despawn: true

# If prevent-despawn is set to true, this determines how many ticks the items will live before they despawn
# 1 tick is equal to 1/20 of a second
despawn-tick-time: 6000

# This is the version of the config.yml file DON'T TOUCH
config-version: 1.0
