# Set to true to prevent dropped items from despawning
prevent-despawn: true

# The number of ticks after which dropped items should despawn.
# A higher value means the items will take longer to despawn.
# 36000 = 30 min / 20 tick = 1 second
despawn-tick-time: 36000

# Set to true to make dropped items appear as if they are glowing
make-glowing: true

# Set to true to show a hologram displaying the player's name above the dropped items
show-hologram: false

