name: detterdeathdrop
version: '${project.version}'
main: betterdeathdrop.betterdeathdrop.BetterDeathDrop
api-version: 1.19
authors: [ laika ]
website: https://hynse.xyz
commands:
  debugtickdespawnnear:
    description: Debug the despawn tick and second of nearby items
    usage: /bdd debugtickdespawnnear <radius>
    permission: betterdeathdrop.debugtickdespawnnear
